# Combine all the *_props.csv files into a single DataFrame and save it as red_channel_df.csv
# The *_props.csv files are generated by the feature extraction script and contain measurements for each cell in the images

from pathlib import Path
import pandas as pd

# INPUT_ROOT = Path(r"N:\Sarah\CHST11KO&P301S project\DAPI, 488 NeuN, 594 AT8, 647 WFA")
INPUT_ROOT = Path(r"N:\Sarah\CHST11KO&P301S project\DAPI, 488 NeuN, 594 AT8, 647 WFA")
folder = INPUT_ROOT / "histograms"

dfs = []
for csv_file in folder.glob("*_props.csv"):
    df = pd.read_csv(csv_file)
    df["image"] = csv_file.stem.removesuffix("_props")
    dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

red_channel_columns = [col for col in combined_df.columns if (col.endswith("_red") or col.startswith("red_"))]

red_channel_df = combined_df[["image", "label"] + red_channel_columns]

red_channel_df.to_csv("../../measurements/red_channel_df.csv", index=False)